spring:
 cloud:
   gateway:
     routes:
       - id: swiggy-app
         uri: lb://JOB-SEARCH
         predicates:
           - Path=/swiggy/**
         filters:
           - AuthenticationFilter

       - id: restaurant-service
         uri: lb://INTERVIEW
         predicates:
           - Path=/restaurant/**
         filters:
           - AuthenticationFilter

       - id: authentication-service
         uri: lb://AUTHENTICATION-SERVICE
         predicates:
           - Path=/auth/**

 application:
   name: SWIGGY-GATEWAY

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/