spring:
 cloud:
   gateway:
     routes:
       - id: jobsearch-app
         uri: lb://JOB-SEARCH
         predicates:
           - Path=/job/**
         filters:
           - AuthenticationFilter

       - id: interview-service
         uri: lb://INTERVIEW
         predicates:
           - Path=/interview/**
         filters:
           - AuthenticationFilter

       - id: authentication-service
         uri: lb://AUTHENTICATION-SERVICE
         predicates:
           - Path=/auth/**

 application:
   name: API-GATEWAY

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/